import type { CountrySeed } from "@/lib/country-seeds/helpers"
import {
    defaultFaq,
    defaultTopFines,
    defaultTopFinesDe,
    getCountryHeaderImages,
    govSource,
} from "@/lib/country-seeds/helpers"

type SeedSources = NonNullable<CountrySeed["source_entries"]>

interface BuildSeedOptions {
    iso2: string
    iso3: string
    name_en: string
    name_local: string
    continent: string
    flag: string
    drive_side: "left" | "right"
    urban: number
    rural: number
    motorway: number
    units?: "km/h" | "mph"
    alcohol: number
    alcoholUnit?: "BAC" | "‰"
    tollsRequired?: boolean
    tollType?: string
    emergency: string[]
    summary: string
    bullets: string[]
    sources: SeedSources
    indexNames?: Record<string, string>
    speedNotes?: string
    alcoholNotes?: string
    tollNotes?: string
    rentalAndIdpNotes?: string
    topFinesCurrency?: string
    status?: CountrySeed["status"]
}

function buildSeed(o: BuildSeedOptions): CountrySeed {
    const currency = o.topFinesCurrency ?? (o.units === "mph" ? "$" : "€")
    return {
        iso2: o.iso2,
        iso3: o.iso3,
        name_en: o.name_en,
        name_local: o.name_local,
        continent: o.continent,
        flag: o.flag,
        indexNames: o.indexNames,
        drive_side: o.drive_side,
        header_images: getCountryHeaderImages(o.iso2),
        quick_answer_bullets: o.bullets,
        top_fines: defaultTopFines(currency),
        faq: defaultFaq(o.name_en, o.indexNames?.de ?? o.name_local),
        source_entries: o.sources,
        sources: o.sources.map((s) => s.publisher ?? s.title),
        summary: o.summary,
        common_traps: o.bullets,
        rental_and_idp_notes:
            o.rentalAndIdpNotes ??
            "Carry your driving licence, vehicle documents, and rental agreement. An International Driving Permit is recommended for non-local licences and may be required by rental companies.",
        last_verified: "2026-05-01",
        status: o.status ?? "verified",
        data_coverage: "medium",
        rules: {
            speed_limits: {
                urban: o.urban,
                rural: o.rural,
                motorway: o.motorway,
                units: o.units ?? "km/h",
                notes: o.speedNotes ?? "Posted signs override default limits.",
            },
            alcohol_limit: {
                value: o.alcohol,
                unit: o.alcoholUnit ?? "BAC",
                notes: o.alcoholNotes ?? "Lower limits may apply to novice or professional drivers.",
            },
            seatbelt_rules: "Mandatory for all occupants.",
            child_seat_rules: "Approved child restraint required for children below local height/age limits.",
            phone_usage_rules: "Handheld phone use while driving is prohibited.",
            headlights_rules: "Use headlights at night, in tunnels, and in poor visibility.",
            priority_rules: "Follow posted signs and local right-of-way rules at intersections.",
            tolls: {
                required: o.tollsRequired ?? false,
                type: o.tollType ?? "none",
                notes: o.tollNotes ?? "",
            },
            parking_rules: "Check local parking signs and paid zones in cities.",
            mandatory_equipment: ["Warning triangle", "Reflective vest"],
            winter_rules: "Winter tyres or chains may be required in mountain or snow regions when signed.",
            emergency_numbers: o.emergency,
        },
    }
}

const eu = (
    iso2: string,
    iso3: string,
    name_en: string,
    name_local: string,
    flag: string,
    opts: Partial<BuildSeedOptions> & {
        sources: SeedSources
        summary: string
        bullets: string[]
    }
) =>
    buildSeed({
        continent: "Europe",
        drive_side: "right",
        urban: 50,
        rural: 90,
        motorway: 130,
        alcohol: 0.05,
        emergency: ["112"],
        iso2,
        iso3,
        name_en,
        name_local,
        flag,
        ...opts,
        sources: opts.sources,
        summary: opts.summary,
        bullets: opts.bullets,
    })

export const COUNTRY_SEEDS: Record<string, CountrySeed> = {
    AD: eu("AD", "AND", "Andorra", "Andorra", "🇦🇩", {
        motorway: 120,
        tollsRequired: true,
        tollType: "toll booth",
        summary: "Andorra has mountain roads and strict winter requirements in snow.",
        bullets: ["Mountain roads need caution", "Winter tyres in snow", "Tolls on main access routes", "Parking limited in towns"],
        sources: [govSource("AD", "gov", "Govern d'Andorra", "https://www.govern.ad/", "Govern d'Andorra")],
    }),
    AL: eu("AL", "ALB", "Albania", "Shqipëria", "🇦🇱", {
        rural: 80,
        motorway: 110,
        summary: "Albania's road network is improving but rural roads can be narrow and poorly lit.",
        bullets: ["Drive defensively on rural roads", "Speed enforcement increasing", "IDP recommended for rentals", "Watch for pedestrians"],
        sources: [govSource("AL", "dpps", "Albanian State Police — Road Safety", "https://www.asp.gov.al/", "ASP")],
    }),
    AT: eu("AT", "AUT", "Austria", "Österreich", "🇦🇹", {
        tollsRequired: true,
        tollType: "vignette",
        tollNotes: "Motorways require a vignette or digital toll.",
        summary: "Motorway vignette required. Strict winter tyre rules and speed enforcement.",
        bullets: ["Vignette required on motorways", "Winter equipment rules apply", "Strict speed cameras", "Parking zones enforced"],
        sources: [
            govSource("AT", "bmi", "BMK — Road traffic", "https://www.bmk.gv.at/", "BMK"),
            govSource("AT", "asfinag", "ASFINAG — Tolls", "https://www.asfinag.at/", "ASFINAG"),
        ],
    }),
    BA: eu("BA", "BIH", "Bosnia and Herzegovina", "Bosna i Hercegovina", "🇧🇦", {
        rural: 80,
        motorway: 130,
        summary: "Mountain roads and winter conditions require extra caution.",
        bullets: ["Winter tyres in snow", "Tolls on some motorways", "IDP recommended", "Watch for slow vehicles"],
        sources: [govSource("BA", "mup", "Ministry of Interior", "https://www.mup.gov.ba/", "MUP BiH")],
    }),
    BE: eu("BE", "BEL", "Belgium", "België", "🇧🇪", {
        summary: "Belgium enforces speed limits strictly, especially in Brussels and Antwerp.",
        bullets: ["Strict speed enforcement", "Low-emission zones in cities", "Priority to the right at unsigned junctions", "Emergency corridor rule on motorways"],
        sources: [govSource("BE", "mobility", "Federal Mobility", "https://mobilit.belgium.be/", "Belgian Mobility")],
    }),
    BG: eu("BG", "BGR", "Bulgaria", "България", "🇧🇬", {
        rural: 90,
        motorway: 140,
        summary: "Bulgaria uses vignettes on motorways and has winter tyre rules in snow.",
        bullets: ["Motorway vignette required", "Winter tyres when snow/ice", "Watch for animal crossings", "Strict alcohol limits"],
        sources: [govSource("BG", "mtitc", "Ministry of Transport", "https://www.mtitc.government.bg/", "MTITC")],
    }),
    BY: eu("BY", "BLR", "Belarus", "Беларусь", "🇧🇾", {
        rural: 90,
        motorway: 110,
        summary: "Check current travel advisories and local registration rules before driving.",
        bullets: ["Check travel advisories", "Registration rules for foreign vehicles", "Zero alcohol for drivers", "Winter driving in snow"],
        sources: [govSource("BY", "mvd", "Ministry of Internal Affairs", "https://mvd.gov.by/", "MVD Belarus")],
    }),
    CH: eu("CH", "CHE", "Switzerland", "Schweiz", "🇨🇭", {
        motorway: 120,
        tollsRequired: true,
        tollType: "vignette",
        summary: "Motorway vignette required. Strict fines and alpine winter rules.",
        bullets: ["Vignette required on motorways", "High fines for speeding", "Winter tyres/chains in Alps", "Tunnel speed limits"],
        sources: [
            govSource("CH", "astag", "ASTRA — Federal Roads Office", "https://www.astra.admin.ch/", "ASTRA"),
            govSource("CH", "fedpol", "Fedpol — Traffic rules", "https://www.fedpol.admin.ch/", "Fedpol"),
        ],
    }),
    CY: eu("CY", "CYP", "Cyprus", "Κύπρος", "🇨🇾", {
        drive_side: "left",
        summary: "Cyprus drives on the left. Tourist areas can be congested in summer.",
        bullets: ["Drive on the left", "Summer congestion in resorts", "Strict drink-drive enforcement", "Mountain roads need care"],
        sources: [govSource("CY", "police", "Cyprus Police", "https://www.police.gov.cy/", "Cyprus Police")],
    }),
    CZ: eu("CZ", "CZE", "Czechia", "Česko", "🇨🇿", {
        summary: "Czechia requires motorway vignettes and enforces zero alcohol for new drivers.",
        bullets: ["Motorway vignette required", "Zero alcohol for novices", "Strict speed cameras", "Winter tyres when required"],
        sources: [govSource("CZ", "md", "Ministry of Transport", "https://www.mdcr.cz/", "MDCR")],
    }),
    DE: eu("DE", "DEU", "Germany", "Deutschland", "🇩🇪", {
        motorway: 130,
        speedNotes: "130 km/h recommended on Autobahn unless signed otherwise.",
        summary: "Right-before-left at unsigned intersections. Strict enforcement on Autobahn and in cities.",
        bullets: ["Right-before-left at junctions", "Autobahn recommended 130 km/h", "Strict speed cameras", "Environmental zones in cities"],
        sources: [
            govSource("DE", "bmvi", "BMVI — Mobility", "https://www.bmvi.de/", "BMVI"),
            govSource("DE", "adac", "ADAC — Traffic law overview", "https://www.adac.de/", "ADAC", ["speed_limits"]),
        ],
    }),
    DK: eu("DK", "DNK", "Denmark", "Danmark", "🇩🇰", {
        summary: "Denmark has many bridges/tunnels with tolls and strict drink-drive limits.",
        bullets: ["Tolls on major bridges", "Strict alcohol limits", "Cyclists have priority", "Winter tyres in snow"],
        sources: [govSource("DK", "vejdirektoratet", "Road Directorate", "https://www.vejdirektoratet.dk/", "Vejdirektoratet")],
    }),
    EE: eu("EE", "EST", "Estonia", "Eesti", "🇪🇪", {
        summary: "Estonia uses vignettes on some national roads and has harsh winter conditions.",
        bullets: ["Road toll/vignette system", "Harsh winter driving", "Strict speed enforcement", "Wildlife on rural roads"],
        sources: [govSource("EE", "mnt", "Transport Administration", "https://www.mnt.ee/", "Maanteeamet")],
    }),
    ES: eu("ES", "ESP", "Spain", "España", "🇪🇸", {
        motorway: 120,
        summary: "Spain enforces speed limits strictly. Many motorways are toll roads.",
        bullets: ["Strict speed enforcement", "Some autopistas are toll roads", "Low-emission zones in cities", "Reflective vest required"],
        sources: [govSource("ES", "dgt", "DGT — Traffic Directorate", "https://www.dgt.es/", "DGT")],
    }),
    FI: eu("FI", "FIN", "Finland", "Suomi", "🇫🇮", {
        summary: "Finland has long winter seasons and strict alcohol limits.",
        bullets: ["Winter tyres mandatory in season", "Moose collision risk", "Strict alcohol limits", "Lower limits on gravel roads"],
        sources: [govSource("FI", "trafi", "Traficom", "https://www.traficom.fi/", "Traficom")],
    }),
    FR: eu("FR", "FRA", "France", "France", "🇫🇷", {
        rural: 80,
        tollsRequired: true,
        tollType: "toll booth",
        summary: "France has extensive toll motorways and priority-to-the-right in towns.",
        bullets: ["Priorité à droite in towns", "Many toll autoroutes", "Crit'Air stickers in cities", "Strict speed cameras"],
        sources: [govSource("FR", "securite-routiere", "Sécurité Routière", "https://www.securite-routiere.gouv.fr/", "Sécurité Routière")],
    }),
    GB: buildSeed({
        iso2: "GB",
        iso3: "GBR",
        name_en: "United Kingdom",
        name_local: "United Kingdom",
        continent: "Europe",
        flag: "🇬🇧",
        drive_side: "left",
        urban: 30,
        rural: 60,
        motorway: 70,
        units: "mph",
        alcohol: 0.08,
        alcoholUnit: "BAC",
        alcoholNotes: "Lower limits in Scotland. Strict enforcement.",
        emergency: ["999", "112"],
        summary: "UK drives on the left. Speed limits in mph with strict camera enforcement.",
        bullets: ["Drive on the left", "Speed limits in mph", "Congestion charges in London", "Strict phone-use fines"],
        topFinesCurrency: "£",
        sources: [
            govSource("GB", "govuk", "GOV.UK — Driving abroad", "https://www.gov.uk/guidance/driving-abroad", "GOV.UK"),
            govSource("GB", "highway-code", "Highway Code", "https://www.gov.uk/guidance/the-highway-code", "DVSA"),
        ],
    }),
    GR: eu("GR", "GRC", "Greece", "Ελλάδα", "🇬🇷", {
        summary: "Greece has many islands accessible by ferry; urban driving can be tight.",
        bullets: ["Ferry planning for islands", "Tight urban streets", "Motorcycle traffic common", "Summer tourist congestion"],
        sources: [govSource("GR", "ypme", "Ministry of Infrastructure", "https://www.ypme.gov.gr/", "YPME")],
    }),
    HR: eu("HR", "HRV", "Croatia", "Hrvatska", "🇭🇷", {
        tollsRequired: true,
        tollType: "toll booth",
        summary: "Croatia's coastal roads are scenic but busy in summer. Motorways are mostly tolled.",
        bullets: ["Tolls on motorways", "Summer coastal congestion", "Vignette/toll for highways", "Watch for tourists on roads"],
        sources: [govSource("HR", "mup", "Ministry of Interior — Traffic", "https://mup.gov.hr/", "MUP")],
    }),
    HU: eu("HU", "HUN", "Hungary", "Magyarország", "🇭🇺", {
        tollsRequired: true,
        tollType: "vignette",
        summary: "Hungary requires motorway e-vignettes and has zero tolerance for drink-driving.",
        bullets: ["Motorway e-vignette required", "Zero alcohol enforcement", "Strict speed cameras", "Budapest congestion"],
        sources: [govSource("HU", "kormany", "Hungarian Government — Transport", "https://kormany.hu/", "Government of Hungary")],
    }),
    IE: eu("IE", "IRL", "Ireland", "Éire", "🇮🇪", {
        drive_side: "left",
        motorway: 120,
        summary: "Ireland drives on the left with many narrow rural roads.",
        bullets: ["Drive on the left", "Narrow rural roads", "Tolls on some motorways", "Strict drink-drive limits"],
        sources: [govSource("IE", "rsa", "Road Safety Authority", "https://www.rsa.ie/", "RSA")],
    }),
    IS: eu("IS", "ISL", "Iceland", "Ísland", "🇮🇸", {
        rural: 80,
        motorway: 90,
        summary: "Iceland has gravel roads, sudden weather changes, and no motorways.",
        bullets: ["Gravel F-roads need 4x4", "Sudden weather changes", "No motorways", "Sheep on roads"],
        sources: [govSource("IS", "island", "Icelandic Road Administration", "https://www.road.is/", "Road.is")],
    }),
    IT: eu("IT", "ITA", "Italy", "Italia", "🇮🇹", {
        tollsRequired: true,
        tollType: "toll booth",
        summary: "Most autostrade are toll roads. ZTL limited-traffic zones are common in historic centres.",
        bullets: ["Autostrada tolls", "ZTL zones in city centres", "Strict speed cameras", "Scooter traffic in cities"],
        sources: [govSource("IT", "mit", "Ministry of Infrastructure", "https://www.mit.gov.it/", "MIT")],
    }),
    LI: eu("LI", "LIE", "Liechtenstein", "Liechtenstein", "🇱🇮", {
        summary: "Liechtenstein shares Swiss vignette rules for motorway access via Switzerland.",
        bullets: ["Swiss vignette for motorway access", "Mountain roads", "Strict enforcement", "Small road network"],
        sources: [govSource("LI", "llv", "Government of Liechtenstein", "https://www.liechtenstein.li/", "LLV")],
    }),
    LT: eu("LT", "LTU", "Lithuania", "Lietuva", "🇱🇹", {
        summary: "Lithuania uses vignettes on some roads and has strict winter requirements.",
        bullets: ["Road user charge/vignette", "Winter tyres in season", "Strict alcohol limits", "Wildlife on rural roads"],
        sources: [govSource("LT", "transport", "Transport Competence Agency", "https://www.transport.lt/", "Transport LT")],
    }),
    LU: eu("LU", "LUX", "Luxembourg", "Luxembourg", "🇱🇺", {
        summary: "Luxembourg has free motorways but dense urban traffic.",
        bullets: ["Motorways toll-free", "Dense rush-hour traffic", "Cross-border commuters", "Strict drink-drive limits"],
        sources: [govSource("LU", "mobilite", "Ministry of Mobility", "https://mobilite.public.lu/", "Mobilité")],
    }),
    LV: eu("LV", "LVA", "Latvia", "Latvija", "🇱🇻", {
        summary: "Latvia requires vignettes on national roads and has harsh winters.",
        bullets: ["Road vignette required", "Winter driving conditions", "Strict speed enforcement", "Riga congestion"],
        sources: [govSource("LV", "csdd", "Road Traffic Safety Directorate", "https://www.csdd.lv/", "CSDD")],
    }),
    MC: eu("MC", "MCO", "Monaco", "Monaco", "🇲🇨", {
        urban: 50,
        summary: "Monaco is extremely dense; parking is limited and fines are high.",
        bullets: ["Very limited parking", "Dense urban traffic", "Strict enforcement", "Plan parking in advance"],
        sources: [govSource("MC", "gouv", "Monaco Government", "https://www.gouv.mc/", "Gouvernement Monaco")],
    }),
    MD: eu("MD", "MDA", "Moldova", "Moldova", "🇲🇩", {
        rural: 90,
        motorway: 110,
        summary: "Road quality varies; check insurance and border requirements.",
        bullets: ["Variable road quality", "Check insurance green card", "IDP recommended", "Winter tyres in snow"],
        sources: [govSource("MD", "mfa", "Ministry of Foreign Affairs", "https://mfa.gov.md/", "MFA Moldova")],
    }),
    ME: eu("ME", "MNE", "Montenegro", "Crna Gora", "🇲🇪", {
        tollsRequired: true,
        tollType: "toll booth",
        summary: "Coastal roads are scenic but narrow; mountain passes need care.",
        bullets: ["Coastal road congestion", "Mountain passes", "Tolls on some routes", "Summer tourist traffic"],
        sources: [govSource("ME", "gov", "Government of Montenegro", "https://www.gov.me/", "Gov.me")],
    }),
    MK: eu("MK", "MKD", "North Macedonia", "Северна Македонија", "🇲🇰", {
        summary: "Mountain roads and winter conditions require cautious driving.",
        bullets: ["Mountain roads", "Winter tyres in snow", "IDP recommended", "Local speed enforcement"],
        sources: [govSource("MK", "mvr", "Ministry of Interior", "https://www.mvr.gov.mk/", "MVR")],
    }),
    MT: eu("MT", "MLT", "Malta", "Malta", "🇲🇹", {
        drive_side: "left",
        summary: "Malta drives on the left with very dense traffic for its size.",
        bullets: ["Drive on the left", "Very dense traffic", "Limited parking", "Narrow streets"],
        sources: [govSource("MT", "transport", "Transport Malta", "https://www.transport.gov.mt/", "Transport Malta")],
    }),
    NL: eu("NL", "NLD", "Netherlands", "Nederland", "🇳🇱", {
        summary: "The Netherlands prioritises cyclists; expect strict traffic enforcement.",
        bullets: ["Watch for cyclists everywhere", "Strict speed cameras", "Many environmental zones", "Congestion on A-roads"],
        sources: [govSource("NL", "rijksoverheid", "Government.nl — Road traffic", "https://www.rijksoverheid.nl/", "Rijksoverheid")],
    }),
    NO: eu("NO", "NOR", "Norway", "Norge", "🇳🇴", {
        summary: "Norway has toll roads, tunnels, and severe winter driving conditions.",
        bullets: ["AutoPASS tolls common", "Long tunnels", "Winter tyres required in season", "Elk on rural roads"],
        sources: [govSource("NO", "vegvesen", "Norwegian Public Roads Administration", "https://www.vegvesen.no/", "Statens vegvesen")],
    }),
    PL: eu("PL", "POL", "Poland", "Polska", "🇵🇱", {
        summary: "Poland requires motorway vignettes and has strict speed enforcement.",
        bullets: ["Motorway e-vignette required", "Strict speed cameras", "Winter tyres in season", "Truck traffic on main roads"],
        sources: [govSource("PL", "gov", "Gov.pl — Road traffic", "https://www.gov.pl/", "Gov.pl")],
    }),
    PT: eu("PT", "PRT", "Portugal", "Portugal", "🇵🇹", {
        tollsRequired: true,
        tollType: "mixed",
        summary: "Many motorways use electronic tolls; register rental plates where required.",
        bullets: ["Electronic tolls on many motorways", "Register rental for tolls", "Coastal wind on bridges", "Strict drink-drive limits"],
        sources: [govSource("PT", "imt", "IMT — Institute of Mobility", "https://www.imt-ip.pt/", "IMT")],
    }),
    RO: eu("RO", "ROU", "Romania", "România", "🇷🇴", {
        motorway: 130,
        tollsRequired: true,
        tollType: "vignette",
        summary: "Romania requires Rovinieta vignette on motorways.",
        bullets: ["Rovinieta vignette required", "Variable road quality", "Strict winter rules in mountains", "Horse-drawn carts on rural roads"],
        sources: [govSource("RO", "mai", "Ministry of Interior", "https://www.mai.gov.ro/", "MAI")],
    }),
    RS: eu("RS", "SRB", "Serbia", "Srbija", "🇷🇸", {
        summary: "Serbia uses toll motorways and requires local insurance.",
        bullets: ["Tolls on motorways", "Local insurance required at border", "Winter tyres in snow", "Belgrade congestion"],
        sources: [govSource("RS", "mup", "Ministry of Interior", "https://www.mup.gov.rs/", "MUP")],
    }),
    SE: eu("SE", "SWE", "Sweden", "Sverige", "🇸🇪", {
        summary: "Sweden has many wildlife collisions and strict drink-drive enforcement.",
        bullets: ["Moose/elk collision risk", "Strict alcohol limits", "Winter tyres in season", "Congestion tax in Stockholm"],
        sources: [govSource("SE", "trafikverket", "Swedish Transport Administration", "https://www.trafikverket.se/", "Trafikverket")],
    }),
    SI: eu("SI", "SVN", "Slovenia", "Slovenija", "🇸🇮", {
        tollsRequired: true,
        tollType: "vignette",
        summary: "Slovenia requires vignettes on motorways and has alpine passes.",
        bullets: ["Motorway vignette required", "Alpine passes", "Winter equipment in snow", "Strict speed enforcement"],
        sources: [govSource("SI", "gov", "Gov.si — Transport", "https://www.gov.si/", "Gov.si")],
    }),
    SK: eu("SK", "SVK", "Slovakia", "Slovensko", "🇸🇰", {
        tollsRequired: true,
        tollType: "vignette",
        summary: "Slovakia requires motorway vignettes and has mountain roads.",
        bullets: ["Motorway vignette required", "Mountain passes", "Winter tyres in snow", "Strict enforcement"],
        sources: [govSource("SK", "minv", "Ministry of Interior", "https://www.minv.sk/", "MinV")],
    }),
    UA: eu("UA", "UKR", "Ukraine", "Україна", "🇺🇦", {
        summary: "Check current travel advisories; driving conditions and rules may change.",
        bullets: ["Check travel advisories", "Variable road conditions", "Strict documentation checks", "Curfew/checkpoints possible"],
        sources: [govSource("UA", "mvs", "Ministry of Internal Affairs", "https://mvs.gov.ua/", "MVS")],
    }),
    XK: eu("XK", "XKX", "Kosovo", "Kosova", "🇽🇰", {
        summary: "Road network is improving; mountain roads need caution in winter.",
        bullets: ["Mountain roads in winter", "IDP recommended", "Local insurance at border", "Speed enforcement increasing"],
        sources: [govSource("XK", "gov", "Government of Kosovo", "https://www.rks-gov.net/", "RKS Gov")],
    }),
    US: buildSeed({
        iso2: "US",
        iso3: "USA",
        name_en: "United States",
        name_local: "United States",
        continent: "North America",
        flag: "🇺🇸",
        drive_side: "right",
        urban: 25,
        rural: 55,
        motorway: 70,
        units: "mph",
        alcohol: 0.08,
        alcoholUnit: "BAC",
        alcoholNotes: "Limits vary by state; many states are 0.08% BAC.",
        emergency: ["911"],
        summary: "Rules vary significantly by state. Right turn on red allowed unless posted otherwise in most states.",
        bullets: ["Rules vary by state", "School bus stop rules are strict", "Right on red common", "Tolls on many East Coast roads"],
        topFinesCurrency: "$",
        sources: [
            govSource("US", "nhtsa", "NHTSA — Road safety", "https://www.nhtsa.gov/", "NHTSA"),
            govSource("US", "dot", "U.S. DOT", "https://www.transportation.gov/", "DOT"),
        ],
    }),
    CA: buildSeed({
        iso2: "CA",
        iso3: "CAN",
        name_en: "Canada",
        name_local: "Canada",
        continent: "North America",
        flag: "🇨🇦",
        drive_side: "right",
        urban: 50,
        rural: 80,
        motorway: 100,
        units: "km/h",
        alcohol: 0.08,
        alcoholUnit: "BAC",
        emergency: ["911"],
        summary: "Canada uses metric speed limits. Winter driving skills essential in many regions.",
        bullets: ["Metric speed limits", "Winter tyres in many provinces", "School bus stop rules", "Wildlife on highways"],
        topFinesCurrency: "C$",
        sources: [govSource("CA", "tc", "Transport Canada", "https://tc.canada.ca/", "Transport Canada")],
    }),
    MX: buildSeed({
        iso2: "MX",
        iso3: "MEX",
        name_en: "Mexico",
        name_local: "México",
        continent: "North America",
        flag: "🇲🇽",
        drive_side: "right",
        urban: 40,
        rural: 80,
        motorway: 110,
        alcohol: 0.08,
        alcoholUnit: "BAC",
        emergency: ["911"],
        summary: "Mexico has toll cuotas on many highways. Avoid driving at night in remote areas.",
        bullets: ["Cuota toll highways", "Topes (speed bumps) common", "Avoid remote night driving", "Insurance recommended"],
        topFinesCurrency: "MX$",
        sources: [govSource("MX", "sct", "Secretariat of Infrastructure", "https://www.gob.mx/sct", "SCT")],
    }),
    BR: buildSeed({
        iso2: "BR",
        iso3: "BRA",
        name_en: "Brazil",
        name_local: "Brasil",
        continent: "South America",
        flag: "🇧🇷",
        drive_side: "right",
        urban: 50,
        rural: 60,
        motorway: 110,
        alcohol: 0.0,
        alcoholUnit: "BAC",
        alcoholNotes: "Zero tolerance — any detectable alcohol is illegal for drivers.",
        emergency: ["190", "192", "193"],
        summary: "Brazil has zero tolerance for alcohol. Many cities use rodízio plate restrictions.",
        bullets: ["Zero alcohol tolerance", "Rodízio plate restrictions in cities", "Tolls on many highways", "Theft risk at traffic lights"],
        topFinesCurrency: "R$",
        sources: [govSource("BR", "gov", "Gov.br — Traffic", "https://www.gov.br/", "Gov.br")],
    }),
    AR: buildSeed({
        iso2: "AR",
        iso3: "ARG",
        name_en: "Argentina",
        name_local: "Argentina",
        continent: "South America",
        flag: "🇦🇷",
        drive_side: "right",
        urban: 40,
        rural: 110,
        motorway: 130,
        alcohol: 0.0,
        alcoholUnit: "BAC",
        alcoholNotes: "Zero tolerance in Buenos Aires and many provinces.",
        emergency: ["911", "107"],
        summary: "Long distances between cities. Patagonia fuel planning essential.",
        bullets: ["Long distances between cities", "Zero alcohol in many areas", "Tolls on autopistas", "Fuel planning in Patagonia"],
        topFinesCurrency: "AR$",
        sources: [govSource("AR", "gcba", "Buenos Aires Government — Traffic", "https://www.buenosaires.gob.ar/", "GCBA")],
    }),
    JP: buildSeed({
        iso2: "JP",
        iso3: "JPN",
        name_en: "Japan",
        name_local: "日本",
        continent: "Asia",
        flag: "🇯🇵",
        indexNames: { en: "Japan", de: "Japan", es: "Japón", ja: "日本" },
        drive_side: "left",
        urban: 40,
        rural: 60,
        motorway: 100,
        alcohol: 0.03,
        alcoholUnit: "BAC",
        alcoholNotes: "Strict enforcement; penalties are severe.",
        tollsRequired: true,
        tollType: "mixed",
        tollNotes: "Most expressways are toll roads; ETC recommended.",
        emergency: ["110", "119"],
        summary: "Japan drives on the left. Stop before railway crossings. No turn on red.",
        bullets: ["Drive on the left", "Stop at railway crossings", "No turn on red", "Expressway tolls common"],
        sources: [
            govSource("JP", "npd", "National Police Agency — Traffic", "https://www.npa.go.jp/", "NPA"),
            govSource("JP", "mlit", "MLIT — Road Bureau", "https://www.mlit.go.jp/", "MLIT"),
        ],
    }),
    KR: buildSeed({
        iso2: "KR",
        iso3: "KOR",
        name_en: "South Korea",
        name_local: "대한민국",
        continent: "Asia",
        flag: "🇰🇷",
        indexNames: { en: "South Korea", de: "Südkorea", es: "Corea del Sur", ja: "韓国" },
        drive_side: "right",
        urban: 50,
        rural: 60,
        motorway: 100,
        alcohol: 0.03,
        alcoholUnit: "BAC",
        tollsRequired: true,
        tollType: "mixed",
        emergency: ["112", "119"],
        summary: "South Korea has strict speed camera enforcement and HI-PASS toll lanes.",
        bullets: ["Strict speed cameras", "HI-PASS toll lanes", "Strict drink-drive limits", "Aggressive urban traffic"],
        sources: [govSource("KR", "police", "Korean National Police", "https://www.police.go.kr/", "KNPA")],
    }),
    AU: buildSeed({
        iso2: "AU",
        iso3: "AUS",
        name_en: "Australia",
        name_local: "Australia",
        continent: "Oceania",
        flag: "🇦🇺",
        drive_side: "left",
        urban: 50,
        rural: 100,
        motorway: 110,
        alcohol: 0.05,
        alcoholUnit: "BAC",
        alcoholNotes: "Limits vary slightly by state.",
        emergency: ["000"],
        summary: "Australia drives on the left. Long outback distances need fuel planning.",
        bullets: ["Drive on the left", "Long outback distances", "Wildlife on roads at dawn/dusk", "Rules vary slightly by state"],
        topFinesCurrency: "A$",
        sources: [govSource("AU", "infrastructure", "Department of Infrastructure", "https://www.infrastructure.gov.au/", "Infrastructure AU")],
    }),
    TH: buildSeed({
        iso2: "TH",
        iso3: "THA",
        name_en: "Thailand",
        name_local: "ประเทศไทย",
        continent: "Asia",
        flag: "🇹🇭",
        drive_side: "left",
        urban: 50,
        rural: 90,
        motorway: 120,
        alcohol: 0.05,
        alcoholUnit: "‰",
        tollsRequired: true,
        tollType: "toll booth",
        emergency: ["191", "1669"],
        summary: "Thailand drives on the left. IDP often checked at police stops.",
        bullets: ["Drive on the left", "IDP often required for tourists", "Tolls on expressways", "Motorbike traffic everywhere"],
        topFinesCurrency: "฿",
        sources: [govSource("TH", "dlt", "Department of Land Transport", "https://www.dlt.go.th/", "DLT")],
    }),
    ID: buildSeed({
        iso2: "ID",
        iso3: "IDN",
        name_en: "Indonesia",
        name_local: "Indonesia",
        continent: "Asia",
        flag: "🇮🇩",
        drive_side: "left",
        urban: 50,
        rural: 80,
        motorway: 100,
        alcohol: 0.0,
        alcoholUnit: "BAC",
        alcoholNotes: "Zero tolerance in practice for drivers.",
        emergency: ["110", "112", "113"],
        summary: "Indonesia drives on the left. Jakarta traffic is among the world's worst.",
        bullets: ["Drive on the left", "Extreme Jakarta congestion", "Motorbike traffic dominant", "International licence + IDP recommended"],
        topFinesCurrency: "Rp",
        sources: [govSource("ID", "korlantas", "National Police Traffic Corps", "https://korlantas.polri.go.id/", "Korlantas")],
    }),
    IN: buildSeed({
        iso2: "IN",
        iso3: "IND",
        name_en: "India",
        name_local: "India",
        continent: "Asia",
        flag: "🇮🇳",
        drive_side: "left",
        urban: 50,
        rural: 80,
        motorway: 100,
        alcohol: 0.03,
        alcoholUnit: "BAC",
        alcoholNotes: "Limits vary by state; many states enforce strictly.",
        emergency: ["112"],
        summary: "India drives on the left. Traffic can be chaotic in cities; horn use is common.",
        bullets: ["Drive on the left", "Chaotic urban traffic", "Cow/animal hazards on roads", "International licence + IDP recommended"],
        topFinesCurrency: "₹",
        sources: [govSource("IN", "morth", "Ministry of Road Transport", "https://morth.nic.in/", "MoRTH")],
    }),
    CN: buildSeed({
        iso2: "CN",
        iso3: "CHN",
        name_en: "China",
        name_local: "中国",
        continent: "Asia",
        flag: "🇨🇳",
        indexNames: { en: "China", de: "China", es: "China", ja: "中国" },
        drive_side: "right",
        urban: 50,
        rural: 80,
        motorway: 120,
        alcohol: 0.02,
        alcoholUnit: "BAC",
        alcoholNotes: "Temporary driving permits required for most foreign visitors.",
        emergency: ["110", "120", "119"],
        summary: "Most foreign visitors cannot use a foreign licence long-term; temporary permits are required.",
        bullets: ["Temporary driving permit usually required", "Strict speed cameras", "Harsh penalties for drink-driving", "Check local city plate restrictions"],
        sources: [govSource("CN", "mps", "Ministry of Public Security", "https://www.mps.gov.cn/", "MPS")],
        status: "sample",
    }),
    TW: buildSeed({
        iso2: "TW",
        iso3: "TWN",
        name_en: "Taiwan",
        name_local: "台灣",
        continent: "Asia",
        flag: "🇹🇼",
        indexNames: { en: "Taiwan", de: "Taiwan", es: "Taiwán", ja: "台湾" },
        drive_side: "right",
        urban: 50,
        rural: 80,
        motorway: 100,
        alcohol: 0.03,
        alcoholUnit: "BAC",
        tollsRequired: true,
        tollType: "mixed",
        emergency: ["110", "119"],
        summary: "Taiwan has extensive freeways with electronic tolls and heavy scooter traffic.",
        bullets: ["Heavy scooter traffic", "Freeway e-tolls", "Mountain roads in east", "Typhoon season driving risks"],
        sources: [govSource("TW", "motc", "Ministry of Transportation", "https://www.motc.gov.tw/", "MOTC")],
    }),
    AE: buildSeed({
        iso2: "AE",
        iso3: "ARE",
        name_en: "United Arab Emirates",
        name_local: "الإمارات",
        continent: "Asia",
        flag: "🇦🇪",
        indexNames: {
            en: "United Arab Emirates",
            de: "Vereinigte Arabische Emirate",
            es: "Emiratos Árabes Unidos",
            ja: "アラブ首長国連邦",
        },
        drive_side: "right",
        urban: 60,
        rural: 100,
        motorway: 140,
        alcohol: 0.0,
        alcoholUnit: "BAC",
        alcoholNotes: "Zero tolerance — any alcohol is illegal for drivers.",
        emergency: ["999", "998", "997"],
        summary: "UAE has modern highways with strict speed cameras and zero alcohol tolerance.",
        bullets: ["Zero alcohol tolerance", "Strict speed cameras on highways", "Salik toll gates in Dubai", "Sandstorms reduce visibility"],
        sources: [govSource("AE", "moi", "Ministry of Interior — Traffic", "https://www.moi.gov.ae/", "MOI UAE")],
    }),
    ZA: buildSeed({
        iso2: "ZA",
        iso3: "ZAF",
        name_en: "South Africa",
        name_local: "South Africa",
        continent: "Africa",
        flag: "🇿🇦",
        indexNames: { en: "South Africa", de: "Südafrika", es: "Sudáfrica", ja: "南アフリカ" },
        drive_side: "left",
        urban: 60,
        rural: 100,
        motorway: 120,
        alcohol: 0.05,
        alcoholUnit: "BAC",
        emergency: ["10111", "10177", "112"],
        summary: "South Africa drives on the left. Avoid driving at night in unfamiliar areas.",
        bullets: ["Drive on the left", "Avoid night driving in remote areas", "Car hijacking risk in some areas", "Animals on rural roads"],
        topFinesCurrency: "R",
        sources: [govSource("ZA", "rtmc", "Road Traffic Management Corporation", "https://www.rtmc.co.za/", "RTMC")],
    }),
}

// Re-export top fines de helper usage note - defaultTopFinesDe unused but kept for future
